### ISSUE TITLE
Error with Flask Scaffold

### ISSUE THREAD

**Issue by chadrockey** [3ll3d00d/ezbeq#72]
I'm seeing import errors when following the installation instructions:

`
Traceback (most recent call last):
  File "/home/chadrockey/python/python/ezbeq/lib/python3.9/site-packages/flask_restx/api.py", line 18, in <module>
    from flask.helpers import _endpoint_from_view_func
ImportError: cannot import name '_endpoint_from_view_func' from 'flask.helpers' (/home/chadrockey/python/python/ezbeq/lib/python3.9/site-packages/flask/helpers.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chadrockey/python/python/ezbeq/bin/./ezbeq", line 5, in <module>
    from ezbeq.main import main
  File "/home/chadrockey/python/python/ezbeq/lib/python3.9/site-packages/ezbeq/main.py", line 10, in <module>
    from flask_restx import Api
  File "/home/chadrockey/python/python/ezbeq/lib/python3.9/site-packages/flask_restx/__init__.py", line 2, in <module>
    from .api import Api  # noqa
  File "/home/chadrockey/python/python/ezbeq/lib/python3.9/site-packages/flask_restx/api.py", line 20, in <module>
    from flask.scaffold import _endpoint_from_view_func
ModuleNotFoundError: No module named 'flask.scaffold'
`

Looks like this was fixed in 2021, but I can't identify what dependency change is causing this.

**Comment by 3ll3d00d** [comment]
It's caused by https://github.com/python-restx/flask-restx/issues/567

Workaround is to run

pip install flask==2.3.3

Before you install ezbeq

**Comment by 3ll3d00d** [comment]
workaround added to https://github.com/3ll3d00d/ezbeq/releases/tag/2.0.0a29
